link:
  forward: TIO_000016
  reverse: TIO_000014
  file: sample.tsv
update:
  frequency: Bimonthly
  method: awk -F '\t' -v db=PDB '$2 == db {print $1 "\t" toupper($3)}' $TOGOID_ROOT/input/interpro/interpro.tsv
