source:
  name: uniprot
  type: Protein
  label: UniProt
  prefix: http://purl.uniprot.org/uniprot/
target:
  name: omim
  type: Phenotype
  label: OMIM
  prefix: http://identifiers.org/mim/
link:
  name: ro
  label: has phenotype
  prefix: http://purl.obolibrary.org/obo/
  predicate: RO_0002200
  directed: false
  file: pair.tsv
update:
  frequency: Monthly
  method: update.pl > pair.tsv 2> log
