source:
  label: Orphanet Rare Disease Ontology
  type: Disease
  namespace:orphanet.ordo
  prefix:	http://identifiers.org/orphanet.ordo/

target:
  label: MeSH
  type: Terminology
  namespace: MeSH
  prefix: http://identifiers.org/mesh/

link:
  file: pair.tsv

  forward:
    label: Related ID of ORPHA
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
    
  reverse:
    label: Related ID of mesh
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: not stable
  method: ordo_Mesh.bash
