source:
  label: Orphanet Rare Disease Ontology
  type: Disease
  namespace: ORPHA
  prefix:	http://identifiers.org/orphanet/

target:
  label: MeSH
  type: Terminology
  namespace: mesh
  prefix: http://identifiers.org/mesh/

link:
  file: pair.tsv

  forward:
    label: Related ID of OMIM
    namespace: oboInOwl
    prefix: http://www.geneontology.org/formats/oboInOwl#
    predicate: hasDbXref

  reverse:
    label: Related ID of mesh
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: not stable
  method: ordo_Mesh.bash
