source:
  namespace: uniprot
  type: Protein
  label: UniProt
  prefix: http://purl.uniprot.org/uniprot/
target:
  namespace: oma
  type: Ortholog
  label: OMA Group
  prefix: http://identifiers.org/oma.grp/
link:
  file: pair.tsv
  forward:
    namespace: orth
    label: is homolog member
    prefix: http://purl.org/net/orth#
    predicate: isHomologMember
  reverse:
    namespace: orth
    label: has homologous
    prefix: http://purl.org/net/orth#
    predicate: hasHomologous
update:
  frequency: Monthly
  method: update.pl > pair.tsv 2> log
