source:
  label: Ensembl
  type: Gene
  namespace: ensembl
  prefix: http://identifiers.org/ensembl/
target:
  label: OMIM
  type: Disease
  namespace: omim
  prefix: http://identifiers.org/omim/
link:
  file: link.tsv
  forward:
    namespace: obo 
    label: is genetic basis for condition
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0004010
  reverse:
    namespace: obo
    label: disease relationship
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0040035
update:
  frequency: Quarterly
  method: LIMIT=10000 ./update.sh > link.tsv
