source:
  namespace: interpro
  type: Protein family
  label: InterPro
  prefix: http://identifiers.org/interpro/
target:
  namespace: pfam
  type: Protein family
  label: Pfam
  prefix: http://identifiers.org/pfam/
link:
  file: pair.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Bimonthly
  method: update.sh PFAM > pair.tsv
