link:
  forward:
    label: has homologous member
    namespace: orth
    prefix: http://purl.org/net/orth#
    predicate: hasHomologousMember
  reverse:
    label: is homologous member
    namespace: orth
    prefix: http://purl.org/net/orth#
    predicate: isHomologousMember
  file: sample.tsv
update:
  frequency: Yearly or less frequently
  method: curl -sSf ftp://ftp.ncbi.nlm.nih.gov/pub/HomoloGene/current/homologene.data | cut -f 1,3
