source:
  name: uniprot
  type: Protein
  label: UniProt
  prefix: http://purl.uniprot.org/uniprot/
target:
  name: chembl.target
  type: Protein
  label: ChEMBL target
  prefix: http://identifiers.org/chembl.target/
link:
  name: rdfs
  label: seeAlso
  prefix: http://www.w3.org/2000/01/rdf-schema#
  predicate: seeAlso
  directed: false
  file: pair.tsv
update:
  frequency: Monthly
  method: update.pl > pair.tsv 2> log
