source:
  namespace: togovar
  type: Variant
  label: TogoVar variant
  prefix: http://togovar.biosciencedbc.jp/variation/
target:
  namespace: enst
  type: Transcript
  label: Ensembl Transcript
  prefix: http://http://rdf.ebi.ac.uk/resource/ensembl.transcript/
link:
  file: pair.tsv
  forward:
    namespace: ro
    label: is located in 
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0001025
update:
  frequency: Monthly
  # NBDC will update the conversion table (tgvid2enst.tsv)  
  method: wget -c https://togovar.biosciencedbc.jp/public/tgvid2enst.tsv && mv tgvid2enst.tsv pair.tsv

