link:
  forward:
    label: in taxon
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002162
  file: sample.tsv
update:
  frequency: Daily
  method: DL='../../input/ncbigene' && mkdir -p $DL && setlock.rb $DL/download.lock "wget -Nq --directory-prefix=$DL ftp.ncbi.nlm.nih.gov/gene/DATA/GENE_INFO/All_Data.gene_info.gz" && gzip -dc $DL/All_Data.gene_info.gz | grep -v '^#' | awk '{print $2"\t"$1}'
