source:
  label: RefSeq Protein
  type: Protein
  namespace: refseq
  prefix: http://identifiers.org/refseq/

target:
  label: UniProt
  type: Protein
  namespace: uniprot
  prefix: http://identifiers.org/uniprot/

link:
  file: pair.tsv

  forward:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: Monthly
  method: wget -q 'ftp://ftp.ncbi.nlm.nih.gov/refseq/uniprotkb/gene_refseq_uniprotkb_collab.gz' && gzip -dc gene_refseq_uniprotkb_collab.gz | grep -v '^#' > pair.tsv && rm gene_refseq_uniprotkb_collab.gz
