source:
  label: RefSeq RNA
  type: Gene
  namespace: refseq
  prefix: http://identifiers.org/refseq/

target:
  label: HGNC
  type: Gene
  namespace: hgnc
  prefix: http://identifiers.org/hgnc/

link:
  file: pair.tsv

  forward:     ####################
    label:     #
    namespace: #  A-TO-DE-KA-KU
    prefix:    #
    predicate: ####################

  reverse:     ####################
    label:     #
    namespace: #  A-TO-DE-KA-KU
    prefix:    #
    predicate: ####################

update:
  frequency: Weekly
  method: wget 'ftp://ftp.ncbi.nlm.nih.gov:/refseq/H_sapiens/mRNA_Prot/human.*.rna.gbff.gz' && gzip -dc human.*.rna.gbff.gz | ./parse_refseq_rna_gbff.pl --hgnc > pair.tsv && rm human.*.rna.gbff.gz
