source:
  name: ko
  type: Ortholog
  label: KEGG Orthology
  prefix: http://identifiers.org/kegg.orthology/
target:
  name: go
  type: Function
  label: Gene Ontology
  prefix: http://purl.obolibrary.org/obo/
link:
  name: ro
  label: functionally related to
  prefix: http://purl.obolibrary.org/obo/
  predicate: RO_0002328
  file: link.tsv
update:
  frequency: Monthly
  method: curl http://rest.genome.jp/link/go/ko | cut -f 1,2 | perl -pe 's/ko://; s/go:/GO_/' > link.tsv
