source:
  label: KEGG Reaction
  type: Reaction
  namespace: kegg.reaction
  prefix: http://identifiers.org/kegg.reaction/
target:
  namespace: ec
  type: Reaction
  label: Enzyme Nomenclature
  prefix: http://identifiers.org/ec-code/
link:
  file: pair.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Monthly
  method: curl http://rest.kegg.jp/link/ec/rn | cut -f 1,2 | perl -pe 's/rn://; s/ec://' > pair.tsv
