link:
  forward:
    label: functionally related to
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002328
  reverse:
    label: gene product of
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002204
  file: sample.tsv
update:
  frequency: Bimonthly
  method: sparql_csv2tsv.sh query.rq http://sparql.med2rdf.org/sparql
