source:
  namespace: chembl.target
  label: ChEMBL target
  type: Protein
  prefix: http://identifiers.org/chembl.target/

target:
  namespace: pdb
  label: PDB
  type: Protein
  prefix: http://identifiers.org/pdb/

link:
  file: pair.tsv

  forward:
    namespace: pdb.id
    label: PDB ID
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: Monthly
  method: https://is.gd/dGwEnj
