link:
  forward: TIO_000004
  reverse: TIO_000007
  file: sample.tsv
update:
  frequency: Weekly
  method: awk -F '\t' 'FNR!=1 && !a[$2 $3]++{print $2 "\t" gensub("GO:","","g",$3)}'
    $TOGOID_ROOT/input/ncbigene/gene2go
