source:
  name: ec-code
  type: Reaction
  label: Enzyme Nomenclature
  prefix: http://identifiers.org/ec-code/
target:
  name: rhea
  type: Reaction
  label: Rhea
  prefix: http://identifiers.org/rhea/
link:
  name: rdfs
  label: seeAlso
  prefix: http://www.w3.org/2000/01/rdf-schema#
  predicate: seeAlso
  directed: false
  file: pair.tsv
update:
  frequency: About six times a year
  method: update.sh
