source:
  namespace: drugbank
  label: DrugBank
  type: Drug
  prefix: http://identifiers.org/drugbank

target:
  namespace: chebi
  label: ChEBI
  type: Chemical compound
  prefix: http://purl.obolibrary.org/obo/chebi#

link:
  file: pair.tsv

  forward:
    label: ChEBI ID
    namespace: chebi.id
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: Monthly
  method: wget https://go.drugbank.com/releases/5-1-8/downloads/all-full-database; unzip all-full-database; python3 make_pairs.py
