source:
  namespace: PDB      
  type: Protein structure
  label: PDB
  prefix: https://rdf.wwpdb.org/pdb/
target:
  namespace: uniprot
  type: Protein
  label: Uniprot
  prefix: http://purl.uniprot.org/uniprot/
link:
  file: pair.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Monthly
  method: update.pl > pair.tsv 2> log
