link:
  file: pair.tsv
  forward:
    namespace: ro
    label: has phenotype
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002200
  reverse:
    namespace: ro
    label: phenotype of
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002201
update:
  frequency: Monthly
  method: Change method update.pl to sparql_thread.pl
