link:
  forward:
    namespace: cco
    label: has target
    prefix: http://rdf.ebi.ac.uk/terms/chembl#
    predicate: hasTarget
  file: pair.tsv
update:
  frequency: Monthly
  method: sparql_csv2tsv.sh query.rq "https://integbio.jp/rdf/mirror/ebi/sparql"
