source:
  label: MBGD (Organism)
  type: Ortholog
  namespace: mbgd
  prefix: http://mbgd.genome.ad.jp/rdf/resource/organism/

target:
  label: NCBI Taxonomy
  type: Taxonomy
  namespace: tax
  prefix: http://identifiers.org/taxonomy/

link:
  file: pair.tsv

  forward:
    label: in taxon
    namespace: intaxon
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002162

update:
  frequency: Monthly
  method: https://is.gd/Lpmycy
