source:
  label: Ensembl
  type: Gene
  namespace: ensembl
  prefix: http://identifiers.org/ensembl/
target:
  label: Ensembl Transcript
  type: Transcript
  namespace: ensembl.transcript
  prefix: http://identifiers.org/ensembl.transcript/
link:
  file: link.tsv
  forward:
    label: transcribed to 
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002511
  reverse:
    label: transcribed from
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002510
update:
  frequency: Quarterly
  method: update.rb --limit all --endpoint https://integbio.jp/rdf/ebi/sparql > link.tsv
