source:
  namespace: dgidb
  type: Drug
  label: DGIdb
  prefix: http://purl.jp/bio/10/dgidb/

target:
  namespace: chemble
  type: Chemical compound
  label: ChEMBL
  prefix: http://rdf.ebi.ac.uk/terms/chembl#
  prefix: http://rdf.ebi.ac.uk/resource/chembl/molecule/CHEMBL553025

link:
  file: pair.tsv

  forward:
    namespace: rdfs
    label: ChEMBL ID
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: Monthly
  method: https://www.dgidb.org/downloads
