source:
  namespace: dgidb
  type: drug-gene interactions
  label: DGIdb ID
  prefix: http://identifiers.org/dgidb/interaction/

target:
  namespace: chemble
  type: Chemical compound
  label: ChEMBL
  prefix: http://rdf.ebi.ac.uk/resource/chembl/molecule/#

link:
  file: pair.tsv

  forward:
    namespace: rdfs
    label: ChEMBL ID
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency:
  method: dgidb-chembl.sh