source:
  name: uniprot
  type: Protein
  label: UniProt
  prefix: http://purl.uniprot.org/uniprot/
target:
  name: refseq
  type: Gene
  label: RefSeq
  prefix: http://identifiers.org/refseq/
link:
  name: ro
  label: Gene product of
  prefix: http://purl.obolibrary.org/obo/
  predicate: RO_0002204
  directed: false
  file: pair.tsv
update:
  date: 2021-02-01
  name: Yuki Moriya
  method: update.pl > pair.tsv 2> log
