source:
  namespace: hgnc
  type: Gene
  label: HGNC
  prefix: http://identifiers.org/hgnc/
target:
  namespace: orphanet
  type: Disease
  label: Orphanet
  prefix: http://identifiers.org/orphanet/
link:
  file: pair.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Bimonthly
  method: ./update.sh orphanet > pair.tsv
