source:
  namespace: togovar
  type: Variant
  label: TogoVar variant
  prefix: http://togovar.biosciencedbc.jp/variation/
target:
  namespace: hgnc
  type: Gene
  label: HGNC Gene
  prefix: http://identifiers.org/hgnc/
link:
  file: pair.tsv
  forward:
    namespace: ro
    label: is associated with 
    prefix: http://togovar.biosciencedbc.jp/vocabulary/
    predicate: http://togovar.biosciencedbc.jp/condition/
update:
  frequency: Monthly
  # NBDC will update the conversion table (tgvid2dbSNP.tsv)  
  method: wget -c https://togovar.biosciencedbc.jp/public/tgvid2clinvar.tsv && mv tgvid2clinvar.tsv pair.tsv

