source:
  label: DrugBank
  type: Drug
  name: drugbank
  prefix: http://identifiers.org/drugbank

target:
  label: ChEMBL
  type: Chemical compound
  name: chemble
  prefix: http://rdf.ebi.ac.uk/terms/chembl#

link:
  file: pair.tsv

  forward:
    label: ChEMBL ID
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: Monthly
  method: wget https://go.drugbank.com/releases/5-1-8/downloads/all-full-database; unzip all-full-database; python3 make_pairs.py
