source:
  namespace: togovar
  type: Variant
  label: TogoVar variant
  prefix: http://togovar.biosciencedbc.jp/variation/
target:
  namespace: ncbig
  type: Gene
  label: NCBI gene 
  prefix: http://purl.uniprot.org/database/
link:
  file: pair.tsv
  forward:
    namespace: ro
    label: is located in
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0001025
update:
  frequency: Monthly
  # NBDC will update the conversion table (tgvid2ncbig.tsv)  
  method: wget -c https://togovar.biosciencedbc.jp/public/tgvid2ncbig.tsv && mv tgvid2ncbig.tsv pair.tsv
