link:
  file: sample.tsv
  forward: TIO_000095
  reverse: TIO_000094
update:
  frequency: Monthly
  method: curl -s https://ddbj.nig.ac.jp/public/rdf/dblink/bioproject-biosample/biosample2bioproject.tsv
