link:
  file: pair.tsv
  forward:
    namespace: orth
    label: is homologous member
    prefix: http://purl.org/net/orth#
    predicate: isHomologousMember
  reverse:
    namespace: orth
    label: has homologous member
    prefix: http://purl.org/net/orth#
    predicate: hasHomologousMember
update:
  frequency: Monthly
  method: update.pl
