link:
  forward:
    label: transcribed from
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002510
  reverse:
    label: transcribed to
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002511
  file: sample.tsv
update:
  frequency: Quarterly
  method: sparql_csv2tsv.sh query.rq https://integbio.jp/rdf/ebi/sparql
