source:
  name: ensembl.protein
  type: Protein
  label: Ensembl Protein
  prefix: http://identifiers.org/ensembl/
target:
  name: ensembl.transcript
  type: Transcript
  label: Ensembl Transcript
  prefix: http://identifiers.org/omim/
link:
  name: obo
  label: ribosomal translation of 
  prefix: http://purl.obolibrary.org/obo/
  predicate: RO_0002512
  directed: true
  file: pair.tsv
update:
  frequency: About four times a year
  method: rm pair.tsv; update.rb --limit all >> pair.tsv
