source:
  namespace: homologene
  type: Ortholog
  label: HomoloGene
  prefix: http://identifiers.org/homologene/
target:
  namespace: ncbigene
  type: Gene
  label: NCBI Gene
  prefix: http://identifiers.org/ncbigene/
link:
  file: link.tsv
  forward:
    namespace: orth
    label: has homologous member
    prefix: http://purl.org/net/orth#
    predicate: hasHomologousMember
  reverse:
    namespace: orth
    label: is homologous member
    prefix: http://purl.org/net/orth#
    predicate: isHomologousMember
update:
  frequency: Yearly or less frequently
  method: curl -sSf ftp://ftp.ncbi.nlm.nih.gov/pub/HomoloGene/current/homologene.data | cut -f 1,3 > link.tsv

