link:
  forward:
    label: in taxon
    namespace: ro
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002162
  file: pair.tsv
update:
  frequency: Monthly
  method: sparql_csv2tsv.sh query.rq "https://integbio.jp/rdf/sparql"
