link:
  forward:
    label: in taxon
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002162
  reverse:
    label: has part
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: BFO_0000051
  file: sample.tsv
update:
  frequency: Yearly
  method: sparql_csv2tsv.sh query.rq http://sparql.nibb.ac.jp/sparql
