source:
  namespace: rhea
  type: Reaction
  label: Rhea
  prefix: http://identifiers.org/rhea/
target:
  namespace: reactome
  type: Pathway
  label: Reactome
  prefix: http://identifiers.org/reactome/
link:
  file: link.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: obo
    label: has component
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002180
update:
  frequency: Bimonthly
  method: update.rb --limit all --endpoint https://integbio.jp/rdf/misc/sparql > link.tsv
