link:
  forward:
    label: evidence publication
    namespace: ro
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002558  # has evidence
  file: sample.tsv
update:
  frequency: threeTimesAYear
  method: sparql_csv2tsv.sh query.rq https://integbio.jp/rdf/ebi/sparql
