link:
  forward:
    namespace: skos
    label: exact match
    prefix: http://www.w3.org/2004/02/skos/core#
    predicate: exactMatch
  file: pair.tsv
update:
  frequency: Monthly
  method: sparql_thread.pl -t 10
