source:
  label: DrugBank
  type: Drug
  name: drugbank
  prefix: http://identifiers.org/drugbank/

target:
  label: KEGG Drug
  type: Drug
  name: kegg.drug
  prefix: http://identifiers.org/kegg.drug/

link:
  file: pair.tsv

  forward:
    label: KEGG Drug ID
    name: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: Monthly
  method: wget https://go.drugbank.com/releases/5-1-8/downloads/all-full-database; unzip all-full-database; python3 make_pairs.py
