link:
  forward: TIO_000025
  reverse: TIO_000024
  file: sample.tsv
update:
  frequency: Weekly
  method: awk -F '\t' -v col=7 'FNR!=1&&$col!="-"&&!a[$2 gensub(/\.[0-9]+$/,"","g",$col)]++{print
    $2 "\t" gensub(/\.[0-9]+$/,"","g",$col)}' $TOGOID_ROOT/input/ncbigene/gene2ensembl
