source:
  namespace: togovar
  type: Variant
  label: TogoVar variant
  prefix: http://togovar.biosciencedbc.jp/variation/
target:
  namespace: ensg
  type: Gene
  label: Ensembl Gene
  prefix: http://rdf.ebi.ac.uk/resource/ensembl/ 
link:
  file: pair.tsv
  forward:
    namespace: ro
    label: is located in  
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0001025
update:
  frequency: Monthly
  # NBDC will update the conversion table (tgvid2ensg.tsv)  
  method: wget -c https://togovar.biosciencedbc.jp/public/tgvid2ensg.tsv && mv tgvid2ensg.tsv pair.tsv

