source:
  label: Ensembl
  type: Gene
  namespae: ensembl
  prefix: http://identifiers.org/ensembl/
target:
  label: HGNC
  type: Gene
  namespace: hgnc
  prefix: http://identifiers.org/hgnc/
link:
  file: link.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Quarterly
  method: LIMIT=10000 update.sh > link.tsv
