link:
  forward:
    label: references
    namespace: dcterms
    prefix: http://purl.org/dc/terms/
    predicate: references
  file: sample.tsv
update:
  frequency: Weekly
  method: DL='../../input/refseq.rna' && mkdir -p $DL && setlock.rb $DL/download.lock "wget -Nq --directory-prefix=$DL ftp://ftp.ncbi.nlm.nih.gov:/refseq/H_sapiens/mRNA_Prot/human.*.rna.gbff.gz" && gzip -dc $DL/human.*.rna.gbff.gz | parse_refseq.rna_gbff.pl --pmid
