source:
  namespace: mondo
  type: Disease
  label: MONDO
  prefix: http://purl.obolibrary.org/obo/
target:
  namespace: omim
  type: Disease
  label: OMIM
  prefix: http://identifiers.org/omim/
link:
  file: link.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: 
  method: update.rb --limit all --endpoint https://integbio.jp/rdf/bioportal/sparql > link.tsv
