link:
  forward:
    label: location of
    namespace: ro
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0001015
  reverse:
    label: is located in
    namespace: ro
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0001025
  file: sample.tsv
update:
  frequency: Bimonthly
  method: gzip -dc $TOGOID_ROOT/input/refseq/human.*.rna.gbff.gz | parse_refseq_rna_gbff.pl --dbsnp | awk -F "\t" '$1 != "" && $2 != ""' | awk '!a[$0]++'
