link:
  forward:
    namespace: ro
    label: has phenotype
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002200
  reverse:
    namespace: ro
    label: phenotype of
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002201
  file: sample.tsv
update:
  frequency: Monthly
  method: sparql_thread.pl -t 10
