link:
  forward:
    label: exactMatch
    namespace: skos
    prefix: http://www.w3.org/2004/02/skos/core#
    predicate: exactMatch
  reverse:
    label: exactMatch
    namespace: skos
    prefix: http://www.w3.org/2004/02/skos/core#
    predicate: exactMatch
  file: sample.tsv
update:
  frequency: threeTimesAYear
  method: sparql_csv2tsv.sh query.rq https://integbio.jp/rdf/pubchem/sparql
