source:
  label: Ensembl Protein
  type: Protein
  namespace: ensembl.protein
  type: Protein
  prefix: http://identifiers.org/ensembl/
target:
  label: Ensembl Transcript
  type: Transcript
  namespace: ensembl.transcript
  prefix: http://identifiers.org/omim/
link:
  file: link.tsv
  forward:
    label: ribosomal translation of 
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002512
  reverse:
    label: ribosomally translates to
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002513
update:
  frequency: Quarterly
  method: update.rb --limit all > link.tsv
