source:
  name: uniprot
  type: Protein
  label: UniProt
  prefix: http://purl.uniprot.org/uniprot/
target:
  name: ensembl
  type: Gene
  label: Ensembl Gene
  prefix: http://identifiers.org/ensembl/
link:
  name: ro
  label: Gene product of
  prefix: http://purl.obolibrary.org/obo/
  predicate: RO_0002204
  file: pair.tsv
update:
  frequency: Monthly
  method: update.pl > pair.tsv 2> log
