link:
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  file: sample.tsv
update:
  frequency: threeTimesAYear
  method: sparql_csv2tsv.sh query.rq https://integbio.jp/rdf/ebi/sparql
