source:
  namespace: drugbank
  label: DrugBank
  type: Drug
  prefix: http://identifiers.org/drugbank

target:
  namespace: mesh
  label: MeSH
  type: 
  prefix: http://id.nlm.nih.gov/mesh/

link:
  file: pair.tsv

  forward:
    namespace: mesh.id
    label: MeSH ID
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0001018  # contained in

update:
  frequency: Monthly
  method: wget https://go.drugbank.com/releases/5-1-8/downloads/all-full-database; unzip all-full-database; python3 make_pairs.py
