source:
  label: RefSeq RNA
  type: Gene
  namespace: refseq
  prefix: http://identifiers.org/refseq/

target:
  label: Taxonomy
  type: Taxonomy
  namespace: taxonomy
  prefix: http://identifiers.org/taxonomy/

link:
  file: pair.tsv

  forward:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: Weekly
  method: wget -q 'ftp://ftp.ncbi.nlm.nih.gov:/refseq/H_sapiens/mRNA_Prot/human.*.rna.gbff.gz' && gzip -dc human.*.rna.gbff.gz | ./parse_refseq_rna_gbff.pl --taxon > pair.tsv && rm human.*.rna.gbff.gz
