link:
  forward:
    namespace: orth
    label: is homologous member
    prefix: http://purl.org/net/orth#
    predicate: isHomologousMember
  reverse:
    namespace: orth
    label: has homologous member
    prefix: http://purl.org/net/orth#
    predicate: hasHomologousMember
  file: sample.tsv
update:
  frequency: Monthly
  method: uniprot_idmapping2tsv.rb ${TOGOID_ROOT}/input/uniprot/idmapping.dat.gz OMA
