link:
  forward:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  file: pair.tsv

update:
  frequency: Monthly
  method: sparql_csv2tsv.sh query.rq https://integbio.jp/rdf/ebi/sparql
