source:
  namespace: uniprot
  type: Protein
  label: UniProt
  prefix: http://purl.uniprot.org/uniprot/
target:
  namespace: pfam
  type: Protein family
  label: Pfam
  prefix: http://identifiers.org/pfam/
link:
  file: pair.tsv
  forward:
    namespace: sio
    label: is member of 
    prefix: http://semanticscience.org/resource/
    predicate: SIO_00095
  reverse:
    namespace: sio
    label: has member
    prefix: http://semanticscience.org/resource/
    predicate: SIO_000059
update:
  frequency: Monthly
  method: update.pl > pair.tsv 2> log
