source:
  namespace: chembl.target
  label: ChEMBL target
  type: Protein
  prefix: http://rdf.ebi.ac.uk/resource/chembl/targetcomponent/

target:
  namespace: go
  label: Gene Ontology
  type: Gene
  prefix: http://identifiers.org/obo.go/

link:
  file: pair.tsv

  forward:
    namespace: go.id
    label: Gene Ontology ID
    #Sparqlクエリに合わせてこのprefix/predicateにしたが、タンパク質→遺伝子ならもっと適切なものが絶対あると思う。
    #Sparqlクエリに合わせるのか、ROからsource ofみたいなのを見つけて当てがうか、どちらがいいのか。
    prefix: http://rdf.ebi.ac.uk/terms/chembl#
    predicate: targetCmptXref

update:
  frequency: Monthly
  method: update.sh > pair.tsv
  #クエリ https://is.gd/7CuouX
