source:
  name: uniprot
  type: Protein
  label: UniProt
  prefix: http://purl.uniprot.org/uniprot/
target:
  name: hgnc
  type: Gene
  label: HGNC
  prefix: http://identifiers.org/hgnc/
link:
  name: ro
  label: Gene product of
  prefix: http://purl.obolibrary.org/obo/
  predicate: RO_0002204
  directed: false
  file: pair.tsv
update:
  date: 2021-01-29
  name: Yuki Moriya
  method: update.pl > pair.tsv

