link:
  forward: TIO_000002
  reverse: TIO_000002
  file: sample.tsv
update:
  frequency: Quarterly
  method: parse_ensembl_genomes_tsv.sh ${TOGOID_ROOT}/input/ensembl_genomes ensembl_protein uniprot
