link:
  forward:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: obo 
    label: has component
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002180
  file: sample.tsv
update:
  frequency: Monthly
  method: sparql_thread.pl -t 10
