source:
  label: KEGG Orthology
  type: Ortholog
  namespace: ko
  prefix: http://identifiers.org/kegg.orthology/
target:
  label: Gene Ontology
  type: Function
  namespace: go
  prefix: http://purl.obolibrary.org/obo/
link:
  file: link.tsv
  forward:
    label: functionally related to
    namespace: ro
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002328
update:
  frequency: Monthly
  method: curl http://rest.genome.jp/link/go/ko | cut -f 1,2 | perl -pe 's/ko://; s/go:/GO_/' > link.tsv
