link:
  forward:
    label: has gene product
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002205
  reverse:
    label: gene product of
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002204
  file: sample.tsv
update:
  frequency: Bimonthly
  method: sparql_csv2tsv.sh query.rq http://sparql.med2rdf.org/sparql
