link:
  forward:
    label: has gene product
    namespace: ro
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002205
  reverse:
    label: gene product of
    namespace: ro
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002204
  file: sample.tsv
update:
  frequency: Quarterly
  method: sparql_taxon.rb query.rq https://integbio.jp/rdf/ebi/sparql $TOGOID_ROOT/input/ensembl/taxonomy.txt
