link:
  file: pair.tsv
  forward:
    namespace: ro
    label: gene product of
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002204
  reverse:
    namespace: ro
    label: has gene product
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002205
update:
  frequency: Monthly
  method: update.pl

