source:
  name: wikipathways
  type: Pathway
  label: WikiPathways
  prefix: http://identifiers.org/wikipathways/
target:
  name: doid
  type: Disease
  label: Disease Ontology 
  prefix: http://purl.obolibrary.org/obo/
link:
  name: rdfs
  label: seeAlso
  prefix: http://www.w3.org/2000/01/rdf-schema#
  predicate: seeAlso
  directed: false
  file: pair.tsv
update:
  frequency: Monthly
  method: update.pl > pair.tsv
