link:
  file: sample.tsv
  forward: TIO_000043
  reverse: TIO_000053
update:
  frequency: Daily
  method: "awk 'BEGIN{ FS=OFS=\"\t\" } $1 ~ /^.RX/ { print $1, $18 }' \"${TOGOID_ROOT}/input/sra/SRA_Accessions.tab\"
    | awk -F'\t' '$1 ~ /^(SR|ER|DR|SAM|PRJ)[A-Z]{1,}[0-9]{1,}/ && $2 ~ /^(SR|ER|DR|SAM|PRJ)[A-Z]{1,}[0-9]{1,}/'"
