source:
  catalog: nbdc02559
  category: Chemical compound
  label: ChEMBL compound
  prefix: http://identifiers.org/chembl.compound/CHEMBL
target:
  catalog: nbdc00641
  type: Chemical compound
  label: PubChem compound
  prefix: https://identifiers.org/pubchem.compound/
link:
  forward:
    label: closeMatch
    namespace: skos
    prefix: http://www.w3.org/2004/02/skos/core#
    predicate: closeMatch
  file: sample.tsv
update:
  frequency: threeTimesAYear
  method: sparql_csv2tsv.sh query.rq https://integbio.jp/rdf/mirror/ebi/sparql
