link:
  forward:
    label: has component
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002180
  reverse:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  file: sample.tsv
update:
  frequency: Monthly
  method: awk -F '\t' '{print $2 "\t" $1}' $TOGOID_ROOT/input/reactome/UniProt2ReactomeReactions.txt
