source:
  label: Ensembl Transcript
  namespace: ensembl.transcript
  type: Transcript
  prefix: http://identifiers.org/ensembl.transcript/
target:
  label: HGNC
  namespace: hgnc
  type: Gene
  prefix: http://identifiers.org/hgnc/
link:
  file: link.tsv
  forward:
    label: transcribed from
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002510
  reverse:
    label: transcribed to
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002511
update:
  frequency: Quarterly
  method: update.rb --limit all --endpoint https://integbio.jp/rdf/ebi/sparql > link.tsv
