source:
  namespace: interpro
  type: Protein family
  label: InterPro
  prefix: http://identifiers.org/interpro/
target:
  namespace: pubmed
  type: Publication
  label: PubMed
  prefix: http://identifiers.org/pubmed/
link:
  file: pair.tsv
  forward:
    namespace: dcterms
    label: references
    prefix: http://purl.org/dc/terms/
    predicate: references
update:
  frequency: Bimonthly
  method: update.sh PUBMED > pair.tsv
