source:
  namespace: uniprot
  type: Protein
  label: UniProt
  prefix: http://purl.uniprot.org/uniprot/
target:
  namespace: ensembl.transcript
  type: Transcript
  label: Ensembl Transcript
  prefix: http://identifiers.org/ensembl/
link:
  file: pair.tsv
  forward:
    namespace: ro
    label: ribosomal translation of
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002512
  reverse:
    namespace: ro
    label: ribosomally translates to
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002513 
update:
  frequency: Monthly
  method: update.pl > pair.tsv 2> log
