source:
  namespace: chembl.target
  label: ChEMBL target
  type: Protein
  prefix: http://identifiers.org/chembl.target/

target:
  namespace: reactome.pathway
  label: Reactome Pathway
  type: Pathway
  prefix: http://identifiers.org/reactome/

link:
  file: pair.tsv

  forward:
    namespace: reactome.pathway.id
    label: Reactome Pathway ID
    # Sparqlクエリでこの述語を用いて検索しているため、そのまま流用した
    prefix: http://rdf.ebi.ac.uk/terms/chembl#
    predicate: targetCmptXref

update:
  frequency: Monthly
  method: update.sh > pair.tsv
  #クエリ https://is.gd/alncsZ
