source:
  namespace: hgnc
  type: Gene
  label: HGNC
  prefix: http://identifiers.org/hgnc/
target:
  namespace: rgd
  type: Gene
  label: RGD
  prefix: http://identifiers.org/rgd/
link:
  file: pair.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Bimonthly
  method: ./update.sh rgd > pair.tsv
