link:
  forward:
    label: disease has basis in
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0004019
  reverse:
    label: causes or contributes to condition
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0003302
  file: sample.tsv
update:
  frequency: 
  method: sparql_csv2tsv.sh query.rq https://togovar-dev.biosciencedbc.jp/sparql
