source:
  label: Orphanet Rare Disease Ontology
  type: Disease
  namespace: orphanet.ordo
  prefix: http://identifiers.org/orphanet.ordo/

target:
  label: Online Mendelian Inheritance in Man
  type: Disease
  namespace: omim.phenotype
  prefix: http://identifiers.org/omim/

link:
  file: pair.tsv

  forward:
    label: related mendelian disease
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

  reverse:
    label: related rare disease
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: not stable
  method: ordo_omim.sh > pair.tsv
