link:
  file: pair.tsv
  forward:
    namespace: skos
    label: exact match
    prefix: http://www.w3.org/2004/02/skos/core#
    predicate: exactMatch
  file: pair.tsv
update:
  frequency: Monthly
  method: update.pl
