#chembl.molecule-chebi
source:
  namespace: chembl.molecule
  type: substance
  label: ChEMBL molecule
  prefix: http://rdf.ebi.ac.uk/resource/chembl/molecule/
target:
  namespace: chebi
  type: substance
  label: ChEBI
  prefix: http://purl.obolibrary.org/obo/chebi#
link:
  file: link.tsv
  forward:
    namespace: skos
    label: closeMatch
    prefix: http://www.w3.org/2004/02/skos/core#
    predicate: closeMatch
update:
  frequency: threeTimesAYear
  method: update.sh > link.tsv