link:
  forward:
    namespace: ro
    label: has phenotype
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002200
  reverse:
    namespace: ro
    label: phenotype of
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002201
  file: pair.tsv
update:
  frequency: Monthly
  method: uniprot_idmapping2tsv.rb ${TOGOID_ROOT}/input/uniprot/idmapping.dat.gz Orphanet
