link:
  forward:
    label: is member of
    namespace: sio
    prefix: http://semanticscience.org/resource/
    predicate: SIO_000095
  reverse:
    label: has member
    namespace: sio
    prefix: http://semanticscience.org/resource/
    predicate: SIO_000059
  file: sample.tsv
update:
  frequency: Monthly
  method: sparql_csv2tsv.sh query.rq https://integbio.jp/rdf/sparql
