source:
  namespace: chembl.target
  label: ChEMBL target
  type: Protein
  prefix: http://identifiers.org/chembl.target/

target:
  namespace: pfam
  label: Pfam
  type: Protein
  prefix: http://identifiers.org/pfam/

link:
  file: pair.tsv

  forward:
    namespace: pfam.id
    label: Pfam ID
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: Monthly
  method: https://is.gd/lawckp
