link:
  forward:
    label: transcribed from
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002510
  reverse:
    label: transcribed to
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002511
  file: sample.tsv
update:
  frequency: Weekly
  method: DL='../../input/refseq.rna' && mkdir -p $DL && setlock.rb $DL/download.lock "wget -Nq --directory-prefix=$DL ftp://ftp.ncbi.nlm.nih.gov:/refseq/H_sapiens/mRNA_Prot/human.*.rna.gbff.gz" && gzip -dc $DL/human.*.rna.gbff.gz | parse_refseq.rna_gbff.pl --geneid
