link:
  forward:
    label: is member of
    namespace: sio
    prefix: http://semanticscience.org/resource/
    predicate: SIO_00095
  reverse:
    label: has member
    namespace: sio
    prefix: http://semanticscience.org/resource/
    predicate: SIO_000059
  file: sample.tsv
update:
  frequency: Monthly
  method: sh retrieve_uniprot_pfam.sh
