#chembl.molecule-pubchem.substance
source:
  namespace: chembl
  type: Chemical compound
  label: ChEMBL compound
  prefix: http://identifiers.org/chembl.compound/
target:
  namespace: pubchem.substance
  type: substance
  label: PubChem substance
  prefix: https://identifiers.org/pubchem.substance/
link:
  file: link.tsv
  forward:
    namespace: skos
    label: closeMatch
    prefix: http://www.w3.org/2004/02/skos/core#
    predicate: closeMatch
update:
  frequency: threeTimesAYear
  method: update.sh > link.tsv