link:
  forward: TIO_000034
  reverse: TIO_000035
  file: sample.tsv
update:
  frequency: Bimonthly
  method: gzip -dc $TOGOID_ROOT/input/refseq/complete.*.rna.gbff.gz | parse_refseq_rna_gbff.pl
    --hgnc |  sed 's/HGNC://' | awk -F "\t" '$1 != "" && $2 != ""' | awk '!a[$0]++'
