link:
  forward:
    namespace: cco
    label: has target
    prefix: http://rdf.ebi.ac.uk/terms/chembl#
    predicate: hasTarget
  file: pair.tsv
update:
  frequency: Monthly
  method: ./sparql_thread_chembl.pl -t 10
