link:
  forward:
    namespace: obo
    label: molecularly interacts with
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002436
  reverse:
    namespace: obo
    label: molecularly interacts with
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002436
  file: sample.tsv
update:
  frequency: Monthly
  method: sparql_thread.pl -t 4
