link:
  forward:
    label: references
    namespace: dcterms
    prefix: http://purl.org/dc/terms/
    predicate: references
  file: sample.tsv
update:
  frequency: Weekly
  method: gzip -dc $TOGOID_ROOT/input/refseq/human.*.rna.gbff.gz | parse_refseq_rna_gbff.pl --pmid | awk -F "\t" '{ if ($1 != "" && $2 != "") print }'
