source:
  namespace: chembl.target
  label: ChEMBL target
  type: Protein
  prefix: http://identifiers.org/chembl.target/

target:
  namespace: interpro
  label: InterPro
  type: Protein
  prefix: http://identifiers.org/interpro/

link:
  file: pair.tsv

  forward:
    namespace: interpro.id
    label: InterPro ID
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: Monthly
  method: update.sh > pair.tsv
  #クエリ https://is.gd/pS9Dcd
