source:
  namespace: uniprot
  type: Protein
  label: UniProt
  prefix: http://purl.uniprot.org/uniprot/
target:
  namespace: go
  type: Function
  label: Gene Ontology
  prefix: http://purl.obolibrary.org/obo/
link:
  file: pair.tsv
  forward:
    namespace: ro
    label: functionally related to
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002328
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Monthly
  method: update.pl > pair.tsv
