link:
  forward:
    namespace: ro
    label: functionally related to
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002328
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  file: pair.tsv
update:
  frequency: Monthly
  method: sparql_thread.pl -t 10 | perl -pe 's/GO_//'
