link:
  forward:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  file: sample.tsv
update:
  frequency: Monthly
  method: wget -q 'ftp://ftp.ncbi.nlm.nih.gov/refseq/uniprotkb/gene_refseq_uniprotkb_collab.gz' && gzip -dc gene_refseq_uniprotkb_collab.gz | grep -v '^#' && rm gene_refseq_uniprotkb_collab.gz
