source:
  namespace: uniprot
  type: Protein
  label: UniProt
  prefix: http://purl.uniprot.org/uniprot/
target:
  namespace: interpro
  type: Protein family
  label: InterPro
  prefix: http://identifiers.org/interpro/
link:
  file: pair.tsv
  forward:
    namespace: sio
    label: protein family
    prefix: http://semanticscience.org/resource/ 
    predicate: SIO_001380
  reverse:
    namespace: sio
    label: has member
    prefix: http://semanticscience.org/resource/
    predicate: SIO_000059
update:
  frequency: Monthly
  method: update.pl > pair.tsv 2> log
