---
source:
  label: SRA Accessions
  type: DataSet
  namespace: sra.accession
  prefix: http://identifiers.org/insdc.sra/
target:
  label: SRA Sample
  type: DataSet
  namespace: sra.sample
  prefix: http://identifiers.org/insdc.sra/
link:
  file: "./sra.accession-sra.sample.tsv"
  forward:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    label: seeAlso
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Daily
  method: "[ $(ls -l /tmp/togoid/SRA_Accessions.tab | awk '{ print $5 }') -eq $(curl
    -sI ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/SRA_Accessions.tab | grep 'Content-Length'
    | tr -d '\r' | awk '{ print $2 }') ] || (mkdir -p $(dirname /tmp/togoid/SRA_Accessions.tab)
    && curl -s ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/SRA_Accessions.tab > /tmp/togoid/SRA_Accessions.tab)
    && awk 'BEGIN{ FS=OFS=\"\t\" } $1 ~ /^.RS/ { print $2, $1 }' /tmp/togoid/SRA_Accessions.tab
    | grep -v '-' > pair.tsv"
