#chembl.molecule-pubchem.substance
source:
  namespace: chembl.molecule
  type: substance
  label: ChEMBL molecule
  prefix: http://rdf.ebi.ac.uk/resource/chembl/molecule/
target:
  namespace: pubchem.substance
  type: substance
  label: PubChem substance
  prefix: http://pubchem.ncbi.nlm.nih.gov/substance
link:
  file: link.tsv
  forward:
    namespace: skos
    label: closeMatch
    prefix: http://www.w3.org/2004/02/skos/core#
    predicate: closeMatch
update:
  frequency: threeTimesAYear
  method: update.sh > link.tsv