source:
  label: Rhea
  type: Reaction
  namespace: rhea
  prefix: http://identifiers.org/rhea/
target:
  label: Enzyme Nomenclature
  type: Reaction
  namespace: ec-code
  prefix: http://identifiers.org/ec-code/
link:
  file: link.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: About six times a year
  method: update.sh > link.tsv
