link:
  forward:
    label: closeMatch
    namespace: skos
    prefix: http://www.w3.org/2004/02/skos/core#
    predicate: closeMatch
  reverse:
    label: closeMatch
    namespace: skos
    prefix: http://www.w3.org/2004/02/skos/core#
    predicate: closeMatch
  file: sample.tsv
update:
  frequency: Weekly
  method: sh retrieve.sh
