source:
  namespace: togovar
  type: Variant
  label: TogoVar variant
  prefix: http://togovar.biosciencedbc.jp/variation/
target:
  namespace: clinvar.vcv
  type: Variant
  label: ClinVar variant
  prefix: http://purl.jp/bio/10/clinvar/accession/
link:
  file: pair.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Monthly
  # NBDC will update the conversion table (tgvid2dbSNP.tsv)  
  method: wget -c https://togovar.biosciencedbc.jp/public/togoid/tgvid2clinvar.tsv && mv tgvid2clinvar.tsv pair.tsv

