source:
  label: Orphanet Rare Disease Ontology
  type: Disease
  namespace: ORPHA
  prefix:	http://identifiers.org/orphanet/

target:
  label: Uniprot
  type: Protein
  namespace: uniprot
  prefix: http://identifiers.org/uniprot/

link:
  file: pair.tsv

  forward:
    label: Related ID of ORDO
    namespace: oboInOwl
    prefix: http://www.geneontology.org/formats/oboInOwl#
    predicate: hasDbXref

  reverse:
    label: Related ID of uniprot
    namespace: rdfs
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso

update:
  frequency: not stable
  method: ordo_uniprot.bash