source:
  namespace: togovar
  type: Variant
  label: TogoVar variant
  prefix: http://togovar.biosciencedbc.jp/variation/
target:
  namespace: refseq
  type: Gene
  label: RefSeq
  prefix: http://identifiers.org/refseq/
link:
  file: pair.tsv
  forward:
    namespace: ro
    label: is located in
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0001025
update:
  frequency: Monthly
  # NBDC will update the conversion table (tgvid2refseqg.tsv)  
  method: wget -c https://togovar.biosciencedbc.jp/public/togoid/tgvid2refseqg.tsv && mv tgvid2refseqg.tsv pair.tsv
