link:
  forward: TIO_000025
  reverse: TIO_000024
  file: sample.tsv
update:
  frequency: Quarterly
  method: parse_ensembl_genomes_tsv.sh ${TOGOID_ROOT}/input/ensembl_genomes ensembl_gene refseq_protein 
