source:
  namespace: togovar
  type: Variant
  label: TogoVar variant
  prefix: http://togovar.biosciencedbc.jp/variation/
target:
  namespace: dbsnp
  type: Variant
  label: dbSNP
  prefix: http://identifiers.org/dbsnp/
link:
  file: pair.tsv
  forward:
    namespace: rdfs
    label: which position is similar to 
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Monthly
  method: update.sh 

