link:
  forward: TIO_000025
  reverse: TIO_000024
  file: sample.tsv
update:
  frequency: Yearly
  method: sparql_csv2tsv.sh mbgd_organism.rq http://sparql.nibb.ac.jp/sparql > mbgd_organism.txt
    && sparql_taxon.rb query.rq http://sparql.nibb.ac.jp/sparql mbgd_organism.txt
