link:
  forward:
    label: has gene product
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002205
  reverse:
    label: gene product of
    namespace: obo
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002204
  file: sample.tsv
update:
  frequency: Yearly
  # method: sparql_csv2tsv.sh query_human.rq http://sparql.nibb.ac.jp/sparql
  method: sparql_csv2tsv.sh mbgd_organism.rq http://sparql.nibb.ac.jp/sparql > mbgd_organism.txt && sparql_taxon.rb query.rq http://sparql.nibb.ac.jp/sparql mbgd_organism.txt
