source:
  namespace: chembl.compound
  type: Chemical compound
  label: ChEMBL compound
  prefix: http://identifiers.org/chembl.compound/
target:
  namespace: chembl.target
  type: Protein
  label: ChEMBL target
  prefix: http://identifiers.org/chembl.target/
link:
  file: pair.tsv
  forward:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Monthly
  method: update.pl > pair.tsv 2> log
