#chembl.molecule-pubmed
source:
  namespace: chembl
  type: Chemical compound
  label: ChEMBL compound
  prefix: http://identifiers.org/chembl.compound/
target:
  namespace: pubmed
  type: Publication
  label: PubMed
  prefix: http://identifiers.org/pubmed/
link:
  file: link.tsv
  forward:
    namespace: obo
    label: evidence publication
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002558  #has evidence
update:
  frequency: threeTimesAYear
  method: update.sh > link.tsv