source:
  label: KEGG Compound
  type: Chemical compound
  namespace: kegg.compound
  prefix: http://identifiers.org/kegg.compound/

target:
  label: ChEBI
  type: Chemical compound
  namespace: ChEBI
  prefix: http://identifiers.org/chebi/

link:
  file: pairs.tsv

  forward:
    label: Equivalent
    namespace: linkdb
    prefix: https://www.genome.jp/linkdb/
    predicate: equivalent
  reverse:
    label: Equivalent
    namespace: linkdb
    prefix: https://www.genome.jp/linkdb/
    predicate: equivalent

update:
  frequency: Quarterly
  method:  python3 make_pairs.py
