source:
  namespace: reactome.reaction
  type: Reaction
  label: Reactome reaction
  prefix: http://identifiers.org/reactome/
target:
  namespace: chebi
  type: Compound
  label: ChEBI
  prefix: http://identifiers.org/chebi/
link:
  file: pair.tsv
  forward:
    namespace: ro
    label: has component
    prefix: http://purl.obolibrary.org/obo/
    predicate: RO_0002180
  reverse:
    namespace: rdfs
    label: seeAlso
    prefix: http://www.w3.org/2000/01/rdf-schema#
    predicate: seeAlso
update:
  frequency: Monthly
  method: update.sh > pair.tsv
