link:
  file: sample.tsv
  forward: TIO_xxxxxx
  reverse: TIO_xxxxxx
update:
  frequency: Monthly
  method: "wget https://ddbj.nig.ac.jp/public/rdf/dblink/metabobank-jga_study/metabobank2jga_study.tsv"
