link:
  forward: TIO_000036
  reverse: TIO_000037
  file: sample.tsv
update:
  frequency: Bimonthly
  method: gzip -dc $TOGOID_ROOT/input/refseq/complete.*.rna.gbff.gz | parse_refseq_rna_gbff.pl
    --protein | awk -F "\t" '$1 != "" && $2 != ""' | awk '!a[$0]++'
