source:
  name: ensembl
  type: Gene
  label: Ensembl
  prefix: http://identifiers.org/ensembl/
target:
  name: ensembl.transcript
  type: Transcript
  label: Ensembl Transcript
  prefix: http://identifiers.org/omim/
link:
  name: obo
  label: transcribed to 
  prefix: http://purl.obolibrary.org/obo/
  predicate: RO_0002511
  directed: true
  file: pair.tsv
update:
  frequency: About four times a year
  method: rm pair.tsv; update.rb >> pair.tsv
